---
title: "GroupProject"
author: "Sarah Gillespie"
date: "2/25/2020"
output: pdf_document
---

```{r include=FALSE, warning=FALSE, message=FALSE, error=FALSE}
# Some customization to format the file, bring in the data you need.  Do not alter.

# knitr settings to control how R chunks work and how the pdf is compiled when knit.
require(knitr)
opts_chunk$set(
  tidy=TRUE,                     # display code as typed
  size="small",                   # slightly smaller font for code
  tidy.opts=list(width.cutoff=65), # wrap text and long comments
  fig.width=7, fig.height=5           #figure size
)


library(ipumsr)
require(tidyverse)
vignette("ipums-cps", package = "ipumsr")
require(Stat2Data)
require(mosaic)
require(tidyverse)
```




```{r}

# get the data in here https://cran.r-project.org/web/packages/ipumsr/vignettes/ipums.html

```


```{r}

# Note that you can pass in the loaded DDI into the `read_ipums_micro()`
cps_ddi <- read_ipums_ddi(ipums_example("cps_00006.xml"))
cps_data <- read_ipums_micro(cps_ddi, verbose = FALSE)

# Currently variable description is available for year
ipums_var_desc(cps_data$YEAR)
#> [1] "YEAR reports the year in which the survey was conducted.  YEARP is repeated on person records."

# But after using ifelse it is gone
cps_data <- cps_data %>%
  mutate(YEAR = ifelse(YEAR == 1962, 62, NA))
ipums_var_desc(cps_data$YEAR)

```


```{r}

# Note that you can pass in the loaded DDI into the `read_ipums_micro()`
USA6_ddi <- read_ipums_ddi("usa_00006.xml")
USA6_data <- read_ipums_micro(USA6_ddi, verbose = FALSE)

# Currently variable description is available for year
ipums_var_desc(USA6_data$YEAR)
#> [1] "YEAR reports the year in which the survey was conducted.  YEARP is repeated on person records."

USA6_dataSMALL <- USA6_data %>%
  select(GQ, FOODSTMP)

```

```{r}

# Note that you can pass in the loaded DDI into the `read_ipums_micro()`
USA7_ddi <- read_ipums_ddi("usa_00007.xml")
USA7_data <- read_ipums_micro(USA7_ddi, verbose = FALSE)

# Currently variable description is available for year
ipums_var_desc(USA7_data$AGE)

ipums_var_desc(USA7_data$PERWT)


USA7_dataSMALL <- USA7_data %>%
  select(ACREHOUS, AGE, AVAILBLE, AGE_HEAD)

```

```{r}
#USA7_PLOT <- ggplot(USA7_dataSMALL, aes(x=AGE, y=AGE_HEAD)) + 
#  geom_point()

#USA7_PLOT

```

```{r}

# Note that you can pass in the loaded DDI into the `read_ipums_micro()`
USA10_ddi <- read_ipums_ddi("usa_00010.xml")
USA10_data <- read_ipums_micro(USA10_ddi, verbose = FALSE)

# Currently variable description is available for year
ipums_var_desc(USA10_data$COSTFUEL)

ipums_var_desc(USA10_data$VALUEH)


USA10_dataSMALL <- USA10_data %>%
  select(GQ, MORTGAGE, COSTELEC, COSTGAS, COSTWATR, COSTFUEL, FOODSTMP, VALUEH, KITCHEN)

# QUESTION: CAN COST OF WATER PREDICT THE COST OF GAS?

USA10_dataUTILITIES <- USA10_dataSMALL %>%
  select(COSTGAS, COSTELEC, COSTWATR, COSTFUEL) %>%
  drop_na(COSTGAS, COSTELEC, COSTWATR, COSTFUEL) %>%
  filter(COSTGAS < 9000) %>%
  filter(COSTWATR < 9000) %>%
  filter(COSTELEC < 9000) %>%
  filter(COSTFUEL < 9000)

# seems to get rid of codes that actually just say whether ga/fent/electricity is included in your home bill

#head(USA10_dataUTILITIES, 8)
#tail(USA10_dataUTILITIES, 12)
#dim(USA10_dataUTILITIES)

USA10_dataUTILITIES_SAMPLE <- sample_n(USA10_dataUTILITIES, 1000)
  


plot <- ggplot(USA10_dataUTILITIES_SAMPLE, aes(x=COSTWATR, y=COSTGAS)) + 
  geom_point()

plot

model_COSTGAS<-lm(COSTGAS~COSTWATR, data=USA10_dataUTILITIES_SAMPLE)
summary(model_COSTGAS)

# so we can conclude "yes": every doller you spend on water means you will also spend about $0.68 more on gas.


m1<-lm(COSTGAS ~ COSTWATR + COSTELEC , data = USA10_dataUTILITIES_SAMPLE)
summary(m1)


```